### PR TITLE
OCaml 5 port

### PR DESCRIPTION
**Pull request by tmcgilchrist**
My work in progress changes to port Reagents to OCaml 5 multicore. The git history is fixed ~~a mess (I'll fix it up once things work~~) but the examples do not all work. 

TODO:
- [x] port to modern dune build
- [x] Replace usages of kcas with Atomics see https://github.com/ocaml-multicore/lockfree/issues/6 and https://github.com/ocaml-multicore/kcas. 
- [x] PR kcas library for updates to opam
- [x] PR lockfree changes to add Michael Scott and Treiber queue. Needs more test coverage. see https://github.com/ocaml-multicore/lockfree/pull/27
- [ ] Add tests for reagents library, working through this about 1/2 the tests/examples pass.

### CODE REVIEW

**Comment by kayceesrk** [comment]
This is starting to look good. Could you comment on why the tests may be failing? Are they failing to build or failing to produce the correct result?

**Comment by bartoszmodelski** [comment]
[PR kcas in opam](https://github.com/ocaml/opam-repository/pull/22554)

**Comment by tmcgilchrist** [comment]
The passing tests and examples run quickly and produce output, I need to validate further it is correct but it appears it is.
The failing examples run but fail to terminate. Looking at the Activity Monitor on macOS they are busily consuming CPU but making no progress. I am going to look into why this week @kayceesrk

**Comment by kayceesrk** [comment]
Thanks Tim.

**Comment by bartoszmodelski** [comment]
## Current state
I spent some time looking at the test failures. I believe that most of them are not related to the changes in this PR or newer OCaml. I have no certainty but here's things I tried: 

* I've built _main_ on 4.12.0+domains and saw the same failures as on 5.0.0+trunk. 
* Changes in this PR look rather innocuous. 
* Some failing tests don't spawn domains, so it's probably not changes in multicore. 

I also zoomed in on the `two_way` test, which assumes two threads of execution trying to communicate twice in a single reagent.
```
time thr A                 thr B 
1      swap chan 1    swap chan 1
2      swap chan 2    swap chan 2
```

It seems to me that is just not supported. In the current code, the first thread to execute will submit an offer for `chan 1` and suspend as its in a _permanent failure_ (using papers lingo). Then the other thread will find the offer on `chan 1` and submit its offer for `chan 2` **without** waking up the first thread. Overall, I don't see how the wake-up would have to happen though - normally the wake-up comes from one thread committing, but in this case, we cannot commit just yet, as we're still in phase I of the protocol. The [paper](https://aturon.github.io/academic/reagents.pdf) kinda leaves this as an exercise to the reader as well (I'm referring to the last paragraph in 5.9).   

## Way forward
Let me know what you think. 

If I'm not mistaken in my diagnosis, the fixes won't be trivial. Thus, I would propose to merge this PR with failures, and I will go over the tests one-by-one.

**Comment by bartoszmodelski** [comment]
Overall, we have the following fails:
* two_way, three_way - known issue https://github.com/ocaml-multicore/reagents/issues/16.
* swap_test - hangs in the same way as two_way (without ever attempting one of the reagents). I think we could detect overlapping cases on merging reactions, but at this point we're not getting this far.
* stack_test_compose - known issue https://github.com/ocaml-multicore/reagents/issues/24.
* stack_test - similar nondeterministic deadlocks as above, probably the same thing. 
* reagent_queue_test, hw_queue - they're both CDL + MSQueue, not sure about the root cause. 
* rec_test - passes on a single domain, not sure about the root cause with multiple.

**Comment by kayceesrk** [comment]
I'm ok with merging this as is and making forward progress.

**Comment by kayceesrk** [comment]
The PR is still marked as draft and cannot be merged as is. @bartoszmodelski you should have merge access now so that you can merge when you think this is ready.

**Comment by bartoszmodelski** [comment]
Great, thanks

**Comment by tmcgilchrist** [comment]
I've tidied up the git history, the 5.0 CI builds and it is using the opam versions of dependencies @bartoszmodelski @kayceesrk

**Pull request merged**
